language: node_js

node_js:
- node

compiler:
- gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

install:
- sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
- sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy main' >> /etc/apt/sources.list.d/mono-xamarin.list"
- sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main' >> /etc/apt/sources.list.d/mono-xamarin.list"
- sudo apt-get update
- sudo apt-get install mono-devel
- export CC="gcc-4.8"
- export CXX="g++-4.8"
- export LINK="gcc-4.8"
- export LINKXX="g++-4.8"
- npm install

script: gulp

after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: docs
  on:
    branch: master

env:
  matrix:
  - secure: fruD3CAy4JP8l/cuPxZRsK3Zz7WYgJnBpmj7tPUsXJ9K9V688puVjJD/pQ6/bgYN62UuoZUEc+ULR7xjWVDGwuAhv0vTR0DgVOS0U7rwTBpWUopxx0gm7QGXinzEM2Upn5b7yXwBK5uY90C0AH6iGWahMn5LhAZnqeVMcw258LjXXM3jvDor0ucQ9lqwBTg7f15J3Lh/ibzLcXDSyJtionvYW/hFmxGX8asrgL8YeGoCq7xR9l2RXafYQpWlLnC7+KvZb8NCflzW7Os5e4W4QvnKFrtmaQxNgDARLE8Yygt+ponOfXdRHoDQY0eeeAcA2HuctGzM/f1lg8tLRc+n6FGvpHl4dg0Zxldnxn8rrsV3BZsGK2jTqITHBvLlT/DSaFMgQV0fVcq+PhneJgFLXaLSX118056bFyYfMOA09bIU4IpQUjJyvCd/VScs2DaGOeTJQ/lI+NbzfVeVFqYBfnZWAeF9u6t4WDr79BBmWnroXS4wdB8IfHmdeeraN3kxysAPCyntd/nBrrLhtTBu+3H0giREyaz3TzX9QP+QJMl7aEJq1t+THT9RR32c8pfTxInHqaYdYvb3WHShYe5Sjqu1+VgGOmpSGSJN5zG9cGVgMJEK4sFcGH7GPWjzrS7HB77fEA99xD3BDOLWrB6NrqFkuUiHrYjVhoFroKSh4dM=
  - secure: Bn01VjiawqXHEtKq+/DFaAYffSWXiK/hUjEafyo8L6zleTU/QQjKgAudLSOcW5OWrAw7OTwQvlGPZvzKi2OHNUsM670n/R1opy5vfvYwUs/pMBjAupIYlOLj8oU64W+MtmReZm+9vkIi1fr9plmvGZqwsoHuXrctHOq2Wil8C3JMpcv9iJh9PS7zthWSB9GQo/MR5iioDaXioiPdwqfCrd1ggdk62/7tMmP6K/n6cFLwS0GyE6sGD7CF+HZzLVO9gRBDUc9LRX9b0/Or/R+IqP53UE9vqw6QaezdJYBS52Jtg4Kq5nPDOeqwIN27uGOI5R3Sy5lP7gbq/MpXlLksewD7NAK73zXPhg5uWdEHq6LulQ4L362lLSomgBlIx9TVc+oGmFtbea7rSvW/r9lnPIb4kmEa5BzyhSkr3OaVOigjas4kOCkaKMweRxTQaVS06aKfuZVD4/Msh95kTJ4iSiO8N8g2mL93DNFUdOCrquIiYpchLAETrQabl0G/NQRvhkJ5sjHhJHsIHbTcYg+fSxg4Hwdn1YHjrLWIU4TopNzaidMr8EXH97baPaRYtBwHRHUBIuuP2SiSyoz6aKAJLl5Aax36QGwQuJ5CSMB64v8KbWmdOAgVV6PwZE6bfNWbUlCaMwuPBcPntKnIZaw61aTft/5yeml+hE4SV2oKBgc=
